language: rust

rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - graphviz
matrix:
  include:
    - rust: nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi

script:
  - |
      travis-cargo build -- --verbose
      travis-cargo run
      travis-cargo test
      travis-cargo bench
      travis-cargo doc -- --no-deps
after_success:
  - touch target/doc/index.html
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
    - secure: "DKEIK2vaRCzWGkEv6fpPhkmszMQBD0lTP5PeNBQ4C6vtRWAGtHdqYxFuXtCIwE264tFYj9zoSZo9Bz+fWCOgvX2nQZwX6MRnMB+jaG+8jo0GynQs8L3Ldwj0MgJJ19+teEa5sR3IGZL94BGbG4bMPoUepTJRrGVXMXry38VFLUjLVBSB3pim7ivc2CWr++Y7s5Rdzrf26IrfjSSHHewW/acNZnSsdrivVt6VfziYVJFEEs6VSmR7Camgoc0VNjQLEP2fMYbnbMuQJ+ftQTYpdbdCoH2R+e3VFMLCpdIccE8RycA2mX1KRJXJSGXmtAhQ30brx1IoStHjtLct0NSQd86SVSjRlkDmyG6hGxehWA1V06HnUSLlJMw0hZT07jVpewmjcWfZAWm5Vg/jeC3qWLo/anVpTiH80CUukkCUZyXkKC6ePFfb84Cf8dgdEvxchUKIH6T6Q+/yePkmn2tKepXadgNgHpoJ6Yp89jJl1e+lEFgh1hw2Wy1rsAgwbKFwZ3/fGz6pDqm+vhfelmQhLHKdwERFIoFOhSjizjajD1CbHO+aZQjznguYO34x/MZ70ZyVB2MiIkn4ujsZ6U41KCS51QQa1XIZOVlNmcMx+GmZLg8eC/H/pwSKaM4LS4websJMjwhRw7EU227YzfefSW6krtushgrWa9s8pVacYT8="
