language: rust

rust:
  - nightly
os:
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
matrix:
  include:
    - rust: nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
script:
  - |
      travis-cargo build -- --verbose
      travis-cargo test
      travis-cargo bench
      travis-cargo doc -- --no-deps
after_success:
  - touch target/doc/index.html
  - travis-cargo --only nightly doc-upload
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
